#! /usr/bin/env bash

vars_() {
  user='samba'
  timezone='Europe/Berlin'
  password='password'
}

install_() {
  dnf update
  dnf install --assumeyes firewalld dnf-automatic samba

  useradd -m "$user"

  (echo "$password"; echo "$password") | smbpasswd -a -s "$user" 

  tee --append /etc/samba/smb.conf /dev/null <<EOF
[share]
        comment = Pictures
        path = /home/${user}/Pictures
        writeable = yes
        browseable = yes
        public = yes
        create mask = 0644
        directory mask = 0755
        write list = user
EOF

  sed --in-place "s@^apply_updates = .*@apply_updates = yes@" /etc/dnf/automatic.conf

  systemctl daemon-reload
  systemctl enable --now dnf-automatic.timer samba.service firewalld.service

  tee /etc/sysctl.d/40-max-user-watches.conf > /dev/null <<EOF
fs.inotify.max_user_watches=524288
EOF

  timedatectl set-"$timezone"

  firewall-cmd --add-service=samba --permanent --quiet
  firewall-cmd --reload --quiet

}

vars_
install_