#! /usr/bin/env bash

vars_() {
  syncthing_gui_address='0.0.0.0:8384'
  user='syncthing'
  timezone='Europe/Berlin'
}

install_() {
  dnf update
  dnf install --assumeyes firewalld dnf-automatic syncthing

  useradd -m "$syncthing_user"

  mkdir /etc/systemd/system/syncthing@.service.d/

  tee /etc/systemd/system/syncthing@.service.d/override.conf /dev/null <<EOF
[Service]
ExecStart=
ExecStart=/usr/bin/syncthing serve --no-browser --no-restart --logflags=0 --gui-address=${syncthing_gui_address}
EOF

  sed --in-place "s@^apply_updates = .*@apply_updates = yes@" /etc/dnf/automatic.conf

  systemctl daemon-reload
  systemctl enable --now dnf-automatic.timer syncthing@"$syncthing_user".service firewalld.service

  tee /etc/sysctl.d/40-max-user-watches.conf > /dev/null <<EOF
fs.inotify.max_user_watches=524288
EOF

  timedatectl set-timezone Europe/Berlin

  firewall-cmd --add-service={syncthing,syncthing-gui} --permanent --quiet
  firewall-cmd --reload --quiet

}

vars_
install_